//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlDente.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficio
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int TipoBeneficioId { get; set; }
        public int ClienteId { get; set; }
        public int RestauranteId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Restaurante Restaurante { get; set; }
        public virtual TipoBeneficio TipoBeneficio { get; set; }
    }
}
