//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlDente.Diagram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<EstadoCliente> EstadoCliente { get; set; }
        public virtual DbSet<EstadoEmpleado> EstadoEmpleado { get; set; }
        public virtual DbSet<EstadoReserva> EstadoReserva { get; set; }
        public virtual DbSet<Mesa> Mesa { get; set; }
        public virtual DbSet<Opinion> Opinion { get; set; }
        public virtual DbSet<Politica> Politica { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<ReservaMesa> ReservaMesa { get; set; }
        public virtual DbSet<Restaurante> Restaurante { get; set; }
        public virtual DbSet<Sancion> Sancion { get; set; }
        public virtual DbSet<TipoSancion> TipoSancion { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
        public virtual DbSet<Beneficio> Beneficio { get; set; }
        public virtual DbSet<PoliticaBeneficio> PoliticaBeneficio { get; set; }
        public virtual DbSet<PoliticaSancion> PoliticaSancion { get; set; }
        public virtual DbSet<TipoBeneficio> TipoBeneficio { get; set; }
    }
}
