//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlDente.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliticaBeneficio
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int TipoBeneficioId { get; set; }
        public int NumeroMinimo { get; set; }
        public int Periodo { get; set; }
        public int EstadoReservaId { get; set; }
        public int RestauranteId { get; set; }
    
        public virtual EstadoReserva EstadoReserva { get; set; }
        public virtual Restaurante Restaurante { get; set; }
        public virtual TipoBeneficio TipoBeneficio { get; set; }
    }
}
