//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlDente.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaMesa
    {
        public int Id { get; set; }
        public int ReservaId { get; set; }
        public int MesaId { get; set; }
    
        public virtual Mesa Mesa { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
